create table bill_status (id bigint not null auto_increment, status varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table connection_type (id integer not null auto_increment, rate integer not null, rental integer not null, `type` varchar(10) not null, primary key (id)) ENGINE=InnoDB;
create table customer (id bigint not null auto_increment, address varchar(255) not null, creation_date date not null, customer_id varchar(10), first_name varchar(20) not null, phone_landline varchar(15), last_name varchar(20) not null, phone_mobile varchar(15), patta_number varchar(255), ward_number integer not null, connection_type varchar(10) not null, primary key (id)) ENGINE=InnoDB;
create table meter (id bigint not null auto_increment, meter_id varchar(255), patta_number varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table meter_reading (id bigint not null auto_increment, reading_date date not null, unit integer not null, patta_number varchar(255) not null, meter_id varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table payment (id bigint not null auto_increment, date_of_payment datetime not null, paid_amount integer not null, ref_payement_status_code bigint not null, ref_payment_type bigint not null, ref_water_bill bigint not null, primary key (id)) ENGINE=InnoDB;
create table payment_status_code (id bigint not null auto_increment, description varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table payment_type (id bigint not null auto_increment, description varchar(255), primary key (id)) ENGINE=InnoDB;
create table water_bill (id bigint not null auto_increment, amount_due integer not null, due_date date not null, net_bill_amount integer, period_from date not null, period_to date not null, previous_due integer, customer_id bigint not null, meter_reading bigint not null, bill_status varchar(255) not null, primary key (id)) ENGINE=InnoDB;
alter table bill_status add constraint STATUS_IDX unique (status);
alter table connection_type add constraint TYPE_IDX unique (type);
alter table customer add constraint PATTA_NUMBER_IDX unique (patta_number);
alter table customer add constraint CUSTOMER_ID_IDX unique (customer_id);
alter table meter add constraint METER_ID_IDX unique (meter_id);
alter table customer add constraint FK_CONNECTION_TYPE foreign key (connection_type) references connection_type (type);
alter table meter add constraint FK_PATTA_NUMBER foreign key (patta_number) references customer (patta_number);
alter table meter_reading add constraint FK_PATTA_NUMBER_MR foreign key (patta_number) references customer (patta_number);
alter table meter_reading add constraint FK_METER_ID foreign key (meter_id) references meter (meter_id);
alter table payment add constraint FK_PAYEMENT_STATUS_CODE foreign key (ref_payement_status_code) references payment_status_code (id);
alter table payment add constraint FK_PAYMENT_TYPE foreign key (ref_payment_type) references payment_type (id);
alter table payment add constraint FK_WATER_BILL foreign key (ref_water_bill) references water_bill (id);
alter table water_bill add constraint FK_CUSTOMER foreign key (customer_id) references customer (id);
alter table water_bill add constraint FK_METER_READING foreign key (meter_reading) references meter_reading (id);
alter table water_bill add constraint FK_BILL_STATUS foreign key (bill_status) references bill_status (status);
